import type { Metadata } from 'next'
import { AlertTriangle, Boxes, CircleDollarSign } from 'lucide-react'

import { adjustInventory } from '@/actions/demo'
import { ActionDialog } from '@/components/forms/action-dialog'
import { KpiCard } from '@/components/dashboard/kpi-card'
import { PageHeader } from '@/components/page-header'
import { Table,TableBody,TableCell,TableHead,TableHeader,TableRow } from '@/components/ui/table'
import { loadDemoData } from '@/data/server'
import { currency, number } from '@/lib/format'

export const metadata: Metadata = { title: 'Inventory' }
export default async function InventoryPage(){const data=await loadDemoData();const disabled=data.source!=='supabase';const low=data.ingredients.filter((item)=>item.current_stock<item.minimum_stock);const value=data.ingredients.reduce((sum,item)=>sum+item.current_stock*item.average_cost,0);const options=data.ingredients.map((item)=>({value:item.id,label:`${item.name} (${item.unit})`}));return <div className="space-y-6"><PageHeader eyebrow="Stock control" title="Inventory" description="Current quantities, thresholds, inventory value, and auditable adjustments." action={<ActionDialog title="Adjust inventory" description="Add, remove, record loss, or correct a fictional stock balance." triggerLabel="New adjustment" submitLabel="Apply adjustment" fields={[{name:'ingredientId',label:'Ingredient',type:'select',options},{name:'adjustmentType',label:'Type',type:'select',options:[{value:'add',label:'Add'},{value:'remove',label:'Remove'},{value:'loss',label:'Loss'},{value:'correction',label:'Correction'}]},{name:'quantity',label:'Quantity',type:'number',required:true,min:0,step:'0.0001'},{name:'reason',label:'Reason',required:true,placeholder:'Inventory count correction'}]} action={adjustInventory} disabled={disabled}/>} /><section className="grid gap-4 sm:grid-cols-3"><KpiCard label="Inventory value" value={currency.format(value)} detail="Weighted average cost" icon={CircleDollarSign}/><KpiCard label="Ingredients tracked" value={number.format(data.ingredients.length)} detail="Across five base units" icon={Boxes} tone="sky"/><KpiCard label="Below minimum" value={number.format(low.length)} detail="Requires attention" icon={AlertTriangle} tone="amber"/></section><div className="overflow-hidden rounded-2xl border bg-white"><Table><TableHeader><TableRow><TableHead>Ingredient</TableHead><TableHead>Supplier</TableHead><TableHead className="text-right">Current</TableHead><TableHead className="text-right">Minimum</TableHead><TableHead className="text-right">Stock value</TableHead><TableHead className="w-32">Level</TableHead></TableRow></TableHeader><TableBody>{data.ingredients.map((item)=>{const ratio=Math.min(100,(item.current_stock/Math.max(item.minimum_stock,1))*100);return <TableRow key={item.id}><TableCell className="font-medium">{item.name}</TableCell><TableCell className="text-slate-500">{item.supplier}</TableCell><TableCell className="text-right">{number.format(item.current_stock)} {item.unit}</TableCell><TableCell className="text-right text-slate-500">{number.format(item.minimum_stock)}</TableCell><TableCell className="text-right">{currency.format(item.current_stock*item.average_cost)}</TableCell><TableCell><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${ratio<100?'bg-amber-500':'bg-emerald-500'}`} style={{width:`${Math.max(5,Math.min(100,ratio))}%`}}/></div></TableCell></TableRow>})}</TableBody></Table></div></div>}
